import type { Evento } from "../types";

export const seedData: { eventos: Evento[] } = {
  eventos: [
    {
      id: "1",
      nombre: "Retiro Corporativo Verano",
      empresa: "TechCorp SA",
      contacto: "Martín Pérez",
      locacion: "Bariloche",
      fecha: "15 Feb 2025",
      pax: 80,
      status: "confirmado",
      cur: "USD",
      cotizado: 53000,
      costo: 31000,
      resp: "Laura",
      tipo: "Corporativo",
    },
    {
      id: "2",
      nombre: "Casamiento Rodriguez-García",
      empresa: "Particular",
      contacto: "Valentina Rodriguez",
      locacion: "Bariloche",
      fecha: "22 Mar 2025",
      pax: 120,
      status: "enviada",
      cur: "USD",
      cotizado: 32000,
      costo: 21000,
      resp: "Melanie",
      tipo: "Casamiento",
    },
    {
      id: "3",
      nombre: "Congreso Farmacéutico Q1",
      empresa: "Pfizer Argentina",
      contacto: "Ana López",
      locacion: "Bariloche",
      fecha: "20 Ene 2025",
      pax: 45,
      status: "negociacion",
      cur: "USD",
      cotizado: 22000,
      costo: 14500,
      resp: "Laura",
      tipo: "Congreso",
    },
    {
      id: "4",
      nombre: "Team Building 2025",
      empresa: "Mercado Libre",
      contacto: "Santiago Ruiz",
      locacion: "Bariloche",
      fecha: "10 Abr 2025",
      pax: 200,
      status: "consulta",
      cur: "ARS",
      cotizado: 0,
      costo: 0,
      resp: "Melanie",
      tipo: "Team Building",
    },
    {
      id: "5",
      nombre: "Retiro Ejecutivo Q4",
      empresa: "Banco Galicia",
      contacto: "María Gómez",
      locacion: "Bariloche",
      fecha: "18 Nov 2024",
      pax: 30,
      status: "perdido",
      cur: "USD",
      cotizado: 15000,
      costo: 9500,
      resp: "Laura",
      tipo: "Ejecutivo",
    },
    {
      id: "6",
      nombre: "Lanzamiento Galaxy S25",
      empresa: "Samsung Argentina",
      contacto: "Diego Fernández",
      locacion: "Bariloche",
      fecha: "08 May 2025",
      pax: 300,
      status: "cotizando",
      cur: "USD",
      cotizado: 0,
      costo: 0,
      resp: "Melanie",
      tipo: "Lanzamiento",
    },
  ],
};

